
AUTO_SHIFT_ENABLE = no
COMBO_ENABLE = no
# CONSOLE_ENABLE = no  # specified in info.json
DEBUG_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
ENCODER_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEJIGGLER_ENABLE = yes
MOUSEKEYS_ENABLE = no
MUSIC_ENABLE = no
POINTING_DEVICE_ENABLE = no
QMK_SETTINGS = no
RGB_MATRIX_CUSTOM_USER = yes
# RGB_MATRIX_ENABLE = yes  # Per-key RGB lights.  # specified in info.json
# RGBLIGHT_ENABLE = yes  # Below-PCB solid color lights.  # specified in info.json
SECURE_ENABLE = no
SPACE_CADET_ENABLE = no  # I can do what I need with mod-tap or tap-dance.
TAP_DANCE_ENABLE = no
VIA_ENABLE = no
# VIAL_ENABLE = no

SRC += uf_init.c
SRC += uf_autocorrect.c
SRC += uf_key_overrides.c
SRC += uf_mousejiggler.c
SRC += uf_numlock.c
SRC += uf_process_record.c
SRC += uf_process_rgb_keycodes.c
# SRC += uf_tapdances.c
